debug: false
Plugin:
  keep_this_up_to_date: true #Oraxen will delete old settings
  language: "english"
  commands:
    repair:
      oraxen_durability_only: false # will not repair vanilla items if set to true
  generation:
    default_assets: true
    default_configs: true
  formatting: # This uses MiniMessage formatting, so legacy colors like §c or &c will not work
    inventory_titles: true # Formats all inventory titles made by any plugin
    titles: true # Formats all titles made by any plugin
    subtitles: true # Formats all subtitles made by any plugin
    action_bar: true # Formats all action bars made by any plugin
    anvil: true # Formats the result item based on the Anvil Text made by any plugin
    signs: true # Formats text on signs when placed or edited
    chat: true # Formats text and glyphs in chat. Disable if using a chat-plugin and you are experiencing issues
    books: true # Formats glyphs in books.
  worldedit: # Please note these are both experimental still and should be used with caution
    noteblock_mechanic: false
    stringblock_mechanic: false # Works, but is buggy with some stringblocks, specifically with Tall-property
  experimental:
    nms:
      block_correction: false # Uses NMS to correct blocks placed against custom blocks

ConfigsTools:
  # list of model data numbers the automatic system will skip
  # List can take ranges like 1..4 as well as normal singular numbers
  skipped_model_data_numbers: [ ]
    # PAPER: 1..4
    # book: 5
    # CLOCK:
    #   - 1
    #   - 4..7
  disable_automatic_model_data: false
  disable_automatic_glyph_code: false
  enable_configs_updater: true
  error_item:
    material: PODZOL
    excludeFromInventory: false # set to true if you don't want to display it inside inventory
    injectID: false

Glyphs:
  emoji_list:
    only_show_emojis_with_permission: true # will only show emojis player has permission to use if set to true
  # Whether Oraxen should register emoji tab completions with unicode characters
  unicode_completions: true
  nms_glyphs: false # Uses NMS to render glyphs instead of the default method

CustomArmor:
  disable_leather_repair: true # Makes custom armor not repairable with leather, only with copies of said custom armor
  shader_type: FANCY # Valid types are FANCY and LESS_FANCY

# This will break Player Heads for all 1.19.4 players and above.
# Until this issue is resolved, this will be disabled by default
Gestures:
  enabled: false # Enabled gesture-mechanic and generates needed files

ItemUpdater:
  # Update the items in player inventory to the latest in config when player joins
  update_items: true
  override_renamed_items: false
  override_item_lore: false # If lore should be overriden, enable to ensure it is identical to the OraxenItem's lore
  update_items_on_reload: true # If Oraxen should update all the items of online players on /oraxen reload items/all

FurnitureUpdater:
  update_furniture: true
  update_on_reload: false # If furniture should be updated on /oraxen reload items/all
  update_on_load: false # If Oraxen should update the FurnitureItem whenever an entity is loaded
  experimental_furniture_type_update: false
  experimental_fix_broken_furniture: false # Attempts to fix furniture that is not placed/broken correctly

Misc:
  # If this is set to true, Oraxen will reset recipes on reload. This might create conflicts with other plugins
  # but this makes the things easier if you want to try your oraxen recipes.
  reset_recipes: true
  # Will add all recipes a player has permission for, to the in-game recipe books
  add_recipes_to_book: true

  hide_scoreboard_numbers: false # This will hide the red numbers on the side of scoreboards
  hide_scoreboard_background: false # This will hide the background of scoreboards

Pack:
  generation:
    generate: true # Unlike Plugin.generation.default_assets, this will enable/disable all pack generation
    # List of file extensions that will not be included in the final zipped ResourcePack
    # ".json", ".png", ".mcmeta" are ignored if added below
    excluded_file_extensions:
      - ".zip"
      - ".bbmodel"
    verify_pack_files: true # Checks all textures and models to make sure they abide by valid Resourcepack formatting
    fix_force_unicode_glyphs: true # Fixes glyphs not being shown when Force Unicode is enabled
    auto_generated_models_follow_texture_path: false
    # 64x32 layer is default size and corresponds to 16. If you need higher
    # resolution, e.g. 128x64, you should set this parameter to 32 and so on.
    armor_resolution: 16
    animated_armor_framerate: 24
    automatically_generate_shader_compatible_armor: true
    generate_armor_shader_files: true
    generate_custom_armor_textures: true
    compression: BEST_COMPRESSION # see Deflater.class
    # protection will use several methods to make your pack impossible to extract
    # with usual tools (native windows unzip, 7zip, winrar, etc) without altering
    # its integrity. Be careful if you activate this option to not try to extract
    # the pack, or you might fill your disk.
    protection: true
    comment: "The content of this texture pack
     \nbelongs to the owner of the Oraxen
     \nplugin and any complete or partial
     \nuse must comply with the terms and
     \nconditions of Oraxen."


  upload:
    enabled: true
    type: polymath #transfer.sh or polymath
    polymath:
      server: atlas.oraxen.com # you can also host your own polymath instance
      secret: "oraxen" # change this if you host your own polymath to limit access to resource pack uploading

  dispatch:
    send_pack: true
    send_on_reload: true
    delay: -1
    mandatory: true
    prompt: "<#fa4943>Accept the pack to enjoy a full <b><gradient:#9055FF:#13E2DA>Oraxen</b><#fa4943> experience"
    join_message:
      enabled: false
      delay: -1

  receive:
    enabled: true
    loaded:
      actions:
        sound:
          # Disabled by default, just switch to enabled to send
          # the below sound whenever someone joins
          enabled: false
          type: minecraft:welcome
          volume: 1.0
          pitch: 1.0
        delay: 5 # delay in ticks
        message:
          enabled: false
          # KICK / CHAT / ACTION_BAR / TITLE
          type: ACTION_BAR
          # Click and Hover elements are only available by using the CHAT type
          content: "<#55ffa4><bold>ResourcePack loaded"
        # If you need to send commands
        commands:
          console: [ ]
          player: [ ]
          opped_player: [ ]

    accepted:
      actions:
        message:
          # KICK / CHAT / ACTION_BAR / TITLE
          type: ACTION_BAR
          # Click and Hover elements are only available by using the CHAT type
          content: "<#55ffa4><bold>ResourcePack accepted"
        # If you need to send commands
        commands:
          console: [ ]
          player: [ ]
          opped_player: [ ]

    denied:
      actions:
        message:
          enabled: false
          # KICK / CHAT / ACTION_BAR / TITLE
          type: CHAT
          # Click and Hover elements are only available by using the CHAT type
          content: "<red>You refused the ResourcePack, but you need it in order to see the new items. Please </red><click:run_command:'/oraxen pack send @p'><hover:show_text:'<green>Display more informations'><green><bold>CLICK HERE</bold></hover></click> <red>or type <bold>/oraxen pack send @p"
        # If you need to send commands
        commands:
          console: [ ]
          player: [ ]
          opped_player: [ ]

    failed_download:
      actions:
        message:
          enabled: false
          # KICK / CHAT / ACTION_BAR / TITLE
          type: CHAT
          # Click and Hover elements are only available by using the CHAT type
          content: "<red>You failed to download the ResourcePack, but you need it in order to see the new items. Please </red><click:run_command:'/oraxen pack send @p'><hover:show_text:'<red>! loading the resourcepack from the game can cause lags'><red><bold>CLICK HERE</bold></hover></click> <red>to retry or type <bold>/oraxen pack send @p</bold>"
        # If you need to send commands
        commands:
          console: [ ]
          player: [ ]
          opped_player: [ ]

oraxen_inventory:
  main_menu_title: "<shift:-18><glyph:menu_items><shift:-193>"
  menu_rows: 6
  menu_layout:
    armors:
      slot: 1
      icon: emerald_chestplate
      title: "<main_menu_title><#362753><glyph:menu_items_overlay:colorable>"
    blocks:
      slot: 2
      icon: orax_ore
      title: "<main_menu_title><#EDCDEB><glyph:menu_items_overlay:colorable>"
    furniture:
      slot: 3
      icon: chair
      title: "<main_menu_title><#F2F2F2><glyph:menu_items_overlay:colorable>"
    flowers:
      slot: 4
      icon: dailily
      title: "<main_menu_title><#bf332c><glyph:menu_items_overlay:colorable>"
    hats:
      slot: 5
      icon: crown
      title: "<main_menu_title><#81B125><glyph:menu_items_overlay:colorable>"
    items:
      slot: 6
      icon: ruby
      title: "<main_menu_title><#DA2E45><glyph:menu_items_overlay:colorable>"
    mystical:
      slot: 7
      icon: legendary_hammer
      title: "<main_menu_title><#9AB2E4><glyph:menu_items_overlay:colorable>"
    plants:
      slot: 8
      icon: weed_leaf
      title: "<main_menu_title><#44C886><glyph:menu_items_overlay:colorable>"
    tools:
      slot: 9
      icon: iron_serpe
      title: "<main_menu_title><#FFFFFF><glyph:menu_items_overlay:colorable>"
    weapons:
      slot: 10
      icon: energy_crystal_sword
      title: "<main_menu_title><#2FB6FF><glyph:menu_items_overlay:colorable>"
